services:
  backend:
    image: heliosryuu/langduck:backend-${TAG:-latest}
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Laravel app
      APP_ENV: local
      APP_DEBUG: "true"
      LARAVEL_PORT: "8000"
      TZ: Asia/Ho_Chi_Minh

      # Database (PostgreSQL)
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_DATABASE: mydb
      DB_USERNAME: myuser
      DB_PASSWORD: secret
    depends_on:
      - postgres
    command: >
      sh -c "php artisan key:generate --force && \
             php artisan migrate --force && \
             php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    image: heliosryuu/langduck:frontend-${TAG:-latest}
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      # Frontend dev server
      FRONTEND_PORT: "5173"
      VITE_API_BASE_URL: http://localhost:8000/api
      TZ: Asia/Ho_Chi_Minh

  postgres:
    image: postgres:17.5-alpine3.22
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      # PostgreSQL setup
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s

volumes:
  postgres-data: